dbt_hol:
  target: dev
  outputs:
    dev:
      type: snowflake
      ######## Please replace with your Snowflake account name
      account: xe71376.ap-south-1.aws
      
      user: dbt_user
      ######## Please replace with your Snowflake dbt user password
      password: nikhil20
      
      role: dbt_dev_role
      database: dbt_hol_dev
      warehouse: dbt_dev_wh
      schema: public
      threads: 200
    prod:
      type: snowflake
      ######## Please replace with your Snowflake account name
      account: xe71376.ap-south-1.aws
      
      user: dbt_user
      ######## Please replace with your Snowflake dbt user password
      password: nikhil20
      
      role: dbt_prod_role
      database: dbt_hol_prod
      warehouse: dbt_prod_wh
      schema: public
      threads: 200